pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - status-success=Check
      - status-success=Test Suite
      - status-success=rust code format style check
      - status-success=clippy_check
    actions:
      merge:
        method: rebase

  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: ask to format code
    conditions:
      - status-failure=rust code format style check
    actions:
        comment:
          message: This pull request does not keep the same code style as this project. Could you fix it? 🙏 Switch to the nightly compiler (with rustup `rustup default nightly`) then run `cargo fmt` to get more details.

  - name: clippy check hint
    conditions:
      - status-failure=clippy_check
    actions:
        comment:
          message: Clippy helps us to improve our Rust code. Could you fix it? 🙏 Run `cargo clippy --all-targets --all-features -- -D warnings` to get more details.

  - name: ask to resolve conflicts
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request now has unresolved conflicts. Could you fix it? 🙏
      
  - name: say hi to the new contributor
    conditions:
      - author!=@rxRust/core-developers
    actions:
        comment:
          message: |
              Welcome to rxRust!
              We're delighted to have you onboard <3
