[package]
name = "rxrust"
version = "1.0.0-alpha.2"
authors = ["adoo <Adoo@outlook.com>"]
edition = "2021"
description = "A Rust implementation of Reactive Extensions."
repository = "https://github.com/rxRust/rxRust"
documentation = "https://docs.rs/rxrust/"
homepage = "https://github.com/rxRust/rxRust"
license="MIT"
keywords = ["reactivex", "rx", "frp"]
categories = ["asynchronous"]
readme = "README.md"

[package.metadata.release]
no-dev-version = true

[dependencies]
smallvec = "1.4.2"

[dependencies.async-std]
version = "1.6.3"
features = ["unstable"]

[dependencies.futures]
version = "0.3.5"
features = ["thread-pool"]

[dependencies.tokio]
version = "1.0"
features = ["rt-multi-thread", "rt"]
optional = true

[dependencies.wasm-bindgen-futures]
version = "0.4.29"
optional = true

[features]
default = ["futures-scheduler"]
tokio-scheduler = ["tokio"]
futures-scheduler = []
wasm-scheduler = ["wasm-bindgen-futures"]

[dev-dependencies]
float-cmp = "0.8.0"
bencher = "0.1.5"
